# Generated by Django 4.1.3 on 2024-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="available_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
